"""Main entrypoint for the FastAPI NimbusTech Ticket Triage service."""

import logging
from typing import List, Optional
from fastapi import FastAPI, HTTPException, status

from ticket_api.models import TicketCreate, TicketUpdate, TicketResponse
from ticket_api.store import store

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ticket_api")

app = FastAPI(
    title="NimbusTech Ticket Triage API",
    description="MVP internal FastAPI service for managing, sorting, and triaging support tickets.",
    version="1.0.0",
)


@app.on_event("startup")
def startup_event():
    """Load the processed tickets report on startup."""
    # The report is generated by Module 1 into data/tickets_report.json
    report_path = "data/tickets_report.json"
    logger.info("Service starting up. Loading tickets from: %s", report_path)
    store.load_from_file(report_path)


@app.get("/", status_code=status.HTTP_200_OK)
def read_root():
    """Basic health/status welcome endpoint (FR11)."""
    return {
        "status": "ok",
        "service": "ticket-triage-api",
        "message": "Welcome to the NimbusTech Ticket Triage and Escalation API.",
    }


@app.get("/tickets", response_model=List[TicketResponse])
def get_tickets():
    """Get the list of all processed tickets, sorted by priority score descending (FR12 + Stretch Goal)."""
    return store.get_all(sort_by_priority=True)


@app.get("/tickets/breached", response_model=List[TicketResponse])
def get_breached_tickets():
    """Get only the tickets that have breached their SLA (FR13)."""
    return store.get_breached()


@app.get("/tickets/summary")
def get_tickets_summary():
    """Get a summary count breakdown of all tickets (Stretch Goal)."""
    return store.get_summary()


@app.get("/tickets/category/{category}", response_model=List[TicketResponse])
def get_tickets_by_category(category: str):
    """Get tickets filtered by category (Stretch Goal)."""
    return store.get_by_category(category)


@app.get("/tickets/{ticket_id}", response_model=TicketResponse)
def get_ticket(ticket_id: str):
    """Get a single ticket by ticket_id. Raises 404 if missing (FR14)."""
    ticket = store.get_by_id(ticket_id)
    if not ticket:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket with ID '{ticket_id}' not found.",
        )
    return ticket


@app.post("/tickets", response_model=TicketResponse, status_code=status.HTTP_201_CREATED)
def create_ticket(ticket: TicketCreate):
    """Add a new ticket record (FR15)."""
    # Check if ticket ID already exists
    if store.get_by_id(ticket.ticket_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Ticket with ID '{ticket.ticket_id}' already exists.",
        )
    new_ticket = store.add(ticket.model_dump())
    return new_ticket


@app.put("/tickets/{ticket_id}", response_model=TicketResponse)
def update_ticket_put(ticket_id: str, update_data: TicketUpdate):
    """Update an existing ticket's status and/or priority_raw (FR16)."""
    updated_ticket = store.update(
        ticket_id,
        priority_raw=update_data.priority_raw,
        status=update_data.status,
    )
    if not updated_ticket:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket with ID '{ticket_id}' not found.",
        )
    return updated_ticket


@app.patch("/tickets/{ticket_id}", response_model=TicketResponse)
def update_ticket_patch(ticket_id: str, update_data: TicketUpdate):
    """Perform a partial update on a ticket's status and/or priority_raw (Stretch Goal)."""
    updated_ticket = store.update(
        ticket_id,
        priority_raw=update_data.priority_raw,
        status=update_data.status,
    )
    if not updated_ticket:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket with ID '{ticket_id}' not found.",
        )
    return updated_ticket


@app.delete("/tickets/{ticket_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ticket(ticket_id: str):
    """Remove a ticket record (FR17)."""
    success = store.delete(ticket_id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket with ID '{ticket_id}' not found.",
        )
    return None
